default:
  image: u_verilator:latest

test-verilator:
  script:
    - echo $PWD
    - ls -l
    - cat /etc/*-release
    - make repository_init
    - which verilator
    - verilator --version
    - ls -l verification/verilator/run.sh
    - chmod u+x verification/verilator/run.sh
    - ls -l verification/verilator/run.sh
    - verification/verilator/run.sh
